### ISSUE TITLE
linux系统下报错

### ISSUE THREAD

**Issue by wilhelmaoi** [ZYKsslm/nonebot_plugin_zyk_lightNVL#2]
windouws系统下能正常登录，获取cookie和查询

但是在linux系统下会报错，报错界面如下

05-11 15:51:48 [ERROR] nonebot | Failed to import "nonebot_plugin_zyk_lightNVL"
Traceback (most recent call last):
  File "/home/zhenxun_bot/bot.py", line 15, in <module>
    nonebot.load_plugins("extensive_plugin")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 45, in load_plugins
    return manager.load_all_plugins()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/zhenxun_bot/extensive_plugin/nonebot_plugin_zyk_lightNVL/__init__.py", line 11, in <module>
    from .work import *
  File "/home/zhenxun_bot/extensive_plugin/nonebot_plugin_zyk_lightNVL/work.py", line 7, in <module>
    from .config import *
  File "/home/zhenxun_bot/extensive_plugin/nonebot_plugin_zyk_lightNVL/config.py", line 9, in <module>
    cookies = load(domain_name="w.linovelib.com")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/browser_cookie3/__init__.py", line 1035, in load
    for cookie in cookie_fn(domain_name=domain_name):
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/browser_cookie3/__init__.py", line 973, in chrome
    return Chrome(cookie_file, domain_name, key_file).load()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/browser_cookie3/__init__.py", line 516, in __init__
    super().__init__(browser='Chrome', cookie_file=cookie_file, domain_name=domain_name, key_file=key_file, **args)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/browser_cookie3/__init__.py", line 331, in __init__
    self.__add_key_and_cookie_file(**kwargs)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/browser_cookie3/__init__.py", line 344, in __add_key_and_cookie_file
    password = _LinuxPasswordManager(USE_DBUS_LINUX).get_password(os_crypt_name)
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.10/lib/python3.10/site-packages/browser_cookie3/__init__.py", line 238, in get_password
    return self.__methods_map.get('kwallet')(os_crypt_name)
TypeError: _LinuxPasswordManager.__get_kdewallet_password_jeepney() missing 1 required positional argument: 'key'

**Comment by ZYKsslm** [comment]
这是第三方库browser_cookie3报错了，请尝试手动获取cookies
